name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: simonverbois/be-energy-monitor
          tags: |
            type=semver,pattern=v{{version}}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.revision=${{ gitea.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push code to GitHub mirror
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPAT_TOKEN }}
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@workflow.local"
          git remote add github "https://x-access-token:${GITHUB_TOKEN}@github.com/simon-verbois/be-energy-monitor.git"
          if [ -d ".gitea" ]; then
            git rm -rf .gitea
            git commit -m "chore: exclude gitea internal files from github mirror"
          fi
          git push --force github HEAD:main --tags

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}